vars: @"../../../vars/hackerrank.d2"
**.style.text-transform: none
classes: @"../../../../classes"
classes: @"../../../../tags"

_quality: {class: compiles}


is_smart_number: {
  label: is_smart_number(num)
  class: op
  sqrt: {
    label: math.sqrt()
    class: op
  }
  val {
    label: val
  }
  condition: {
    label: val ^ 2 == num
    class: cond
  }
  result: {
    True
    False
  }
  sqrt -> val
  val -> condition
  condition -> result.True: print { class: positive }
  condition -> result.False: print { class: negative }
}


design_pattern: {
  label: "design pattern: none"
  link: ../../../design-patterns/none.d2
  class: _link
}
