frontend: {
  style: {
    stroke: SteelBlue
    stroke-width: 5
  }
}
pipeline: {
  style: {
    stroke: SteelBlue
    stroke-width: 5
  }
}
api: {
  style: {
    stroke-width: 5
    stroke: DarkSlateGray
  }
}
database: {
  style: {
    stroke: SeaGreen
    stroke-width: 5
  }
}
aws: {
  style: {
    stroke: Goldenrod
    stroke-width: 5
  }
}
azure: {
  style: {
    stroke: Goldenrod
    stroke-width: 5
  }
}
gcp: {
  style: {
    stroke: Goldenrod
    stroke-width: 5
  }
}
