direction: down
vars: @"../../../vars/hackerrank.d2"
**.style.text-transform: none
classes: @"../../../../tags"
classes: @"../../../../classes"

_quality: {class: compiles}

kangaroo: {
  label: kangaroo(x1, v1, x2, v2)
  conditions: "" {
    class: cond
    description: |md
    ## vertical OR slope
    ### vertical
    * hop is down
    * v_2 >= v_1
    ### slope
    * diffs don\'t divide evenly
    * not (x2-x1) \% (v1 - v2) == 0
    |
  }
  conditions -> result: "YES" {
    style.stroke: darkred
  }
  conditions -> result: "NO" {
    style.stroke: darkgreen
  }
}

design_pattern: {
  label: "design pattern: none"
  link: ../../../design-patterns/none.d2
  class: _link
}
