direction: down
vars: {
  d2-config: {
    theme-id: 201
    layout-engine: elk
  }
}

classes: @"../../../classes/tags"

_quality: {class: compiles}

birthday: {
  label: birthday(s, d, m)
  iter: iter\; leave space for segment
  # TODO: illustrate "leave space for segment"
  cond: check if segment sums to d
  result
  iter -> cond
  cond -> result: increment
}

