direction: down
vars: {
  d2-config: {
    theme-id: 201
    layout-engine: elk
  }
}

classes: @"../../../classes/tags"

# TODO: replace styles with classes

_quality: {class: compiles}

maximumPerimeterTriangle {
  label: maximumPerimeterTriangle(sticks)
  sort: sort\ndescending
  iter: i in range(len(sticks)-2)
    cond: isTriangle\nC < B + A {
      shape: diamond
      y: {
        label: sorted\nedges
        shape: circle
        style: {
          stroke: darkgreen
        }
      }
      n: {
        label: "[-1]"
        shape: circle
        style: {
          stroke: crimson
        }
      }
    }
  result
  sort -> iter
  iter -> cond
  cond.y -> result: {
    style: {
      stroke: darkgreen
    }
  }
  cond.n -> result: {
    style: {
      stroke: crimson
    }
  }
}
