direction: down
vars: {
  d2-config: {
    theme-id: 201
    layout-engine: elk
  }
}

classes: @"../../../classes/tags"

_quality: {class: compiles}

sockMerchant {
  label: sockMerchant(n, ar)
  result: result\ninit 0
  iter: i in range(n)
  cond: elem in hash {
    shape: diamond
  }
  iter -> cond
  cond -> result: yes {
    style: {
      stroke: darkgreen # TODO: use classes, not styles
    }
  }
  cond -> result: no {
    style: {
      stroke: crimson
    }
  }
  # TODO: what's actually returned? 
}
