vars: @"../vars/jbm.d2"
classes: @"../../classes"
classes: @"../../tags"
layers: {
  0_base: {
    **.style.text-transform: none
    grid-rows: 2
    context: |md
      ## None
      These diagrams do not correspond to any\
      software design pattern.
    |
    tech_sd_notes_designs: {
      label: "tech/sd-notes/designs (1)"
      grid-columns: 1
      n_pastebin: {
        label: "pastebin.d2"
        link: ../sd-notes/designs/pastebin.d2
        class: _link
      }
    }
    tech_self: {
      label: "tech/self (1)"
      grid-columns: 1
      n_seq_tagging: {
        label: "seq_tagging.d2"
        link: ../self/seq_tagging.d2
        class: _link
      }
    }
    tech_my_chess: {
      label: "tech/my-chess (1)"
      grid-columns: 1
      n_seq_prototype_shiny: {
        label: "seq_prototype_shiny.d2"
        link: ../my-chess/seq_prototype_shiny.d2
        class: _link
      }
    }
    tech_dev: {
      label: "tech/dev (3)"
      grid-columns: 1
      n_docker_recreate_bug: {
        label: "docker-recreate-bug.d2"
        link: ../dev/docker-recreate-bug.d2
        class: _link
      }
      n_make: {
        label: "make.d2"
        link: ../dev/make.d2
        class: _link
      }
      n_zombie_processes: {
        label: "zombie-processes.d2"
        link: ../dev/zombie-processes.d2
        class: _link
      }
    }
    tech_sd_notes_tools: {
      label: "tech/sd-notes/tools (8)"
      grid-columns: 1
      n_NoSQL: {
        label: "NoSQL.d2"
        link: ../sd-notes/tools/NoSQL.d2
        class: _link
      }
      n_RAG: {
        label: "RAG.d2"
        link: ../sd-notes/tools/RAG.d2
        class: _link
      }
      n_communication: {
        label: "communication.d2"
        link: ../sd-notes/tools/communication.d2
        class: _link
      }
      n_rdbms: {
        label: "rdbms.d2"
        link: ../sd-notes/tools/rdbms.d2
        class: _link
      }
      n_rdbms_scaling: {
        label: "rdbms_scaling.d2"
        link: ../sd-notes/tools/rdbms_scaling.d2
        class: _link
      }
      n_rdbms_systems: {
        label: "rdbms_systems.d2"
        link: ../sd-notes/tools/rdbms_systems.d2
        class: _link
      }
      n_rdbms_tuning: {
        label: "rdbms_tuning.d2"
        link: ../sd-notes/tools/rdbms_tuning.d2
        class: _link
      }
      n_vector_database: {
        label: "vector_database.d2"
        link: ../sd-notes/tools/vector_database.d2
        class: _link
      }
    }
    tech_hi: {
      label: "tech/hi (10)"
      grid-columns: 1
      alembic: {
        label: "alembic.d2"
        link: ../hi/alembic.d2
        class: _link
      }
      n_seq_auth: {
        label: "seq_auth.d2"
        link: ../hi/seq_auth.d2
        class: _link
      }
      n_seq_basic_usage: {
        label: "seq_basic_usage.d2"
        link: ../hi/seq_basic_usage.d2
        class: _link
      }
      n_seq_data_sync: {
        label: "seq_data_sync.d2"
        link: ../hi/seq_data_sync.d2
        class: _link
      }
      n_seq_enrich_glosses: {
        label: "seq_enrich_glosses.d2"
        link: ../hi/seq_enrich_glosses.d2
        class: _link
      }
      n_seq_fetch_text: {
        label: "seq_fetch_text.d2"
        link: ../hi/seq_fetch_text.d2
        class: _link
      }
      n_seq_frontend: {
        label: "seq_frontend.d2"
        link: ../hi/seq_frontend.d2
        class: _link
      }
      n_seq_generate_audio: {
        label: "seq_generate_audio.d2"
        link: ../hi/seq_generate_audio.d2
        class: _link
      }
      n_seq_migration: {
        label: "seq_migration.d2"
        link: ../hi/seq_migration.d2
        class: _link
      }
      n_seq_process_sentences: {
        label: "seq_process_sentences.d2"
        link: ../hi/seq_process_sentences.d2
        class: _link
      }
    }
    _quality: {class: styled}
  }
}
