vars: @"../vars/jbm.d2"
classes: @"../../classes"
classes: @"../../tags"

layers: {
  0_base: {
    **.style.text-transform: none
    grid-rows: 2
    context: |md
      ## None
      These diagrams do not correspond to any\
      software design pattern.
    |
    tech_sd_notes_designs: {
      label: "sd-notes/designs"
      grid-columns: 1
      n_pastebin: {
        label: "pastebin.d2"
        link: ../sd-notes/designs/pastebin.d2
        class: _link
      }
    }
    tech_self: {
      label: "self"
      grid-columns: 1
      n_tagging: {
        label: "tagging.d2"
        link: ../self/tagging.d2
        class: _link
      }
    }
    tech_my_chess: {
      label: "my-chess"
      grid-columns: 1
      n_prototype_shiny: {
        label: "prototype_shiny.d2"
        link: ../my-chess/prototype_shiny.d2
        class: _link
      }
    }
    tech_dev: {
      label: "dev"
      grid-columns: 1
      n_docker_recreate_bug: {
        label: "docker-recreate-bug.d2"
        link: ../dev/docker-recreate-bug.d2
        class: _link
      }
      n_make: {
        label: "make.d2"
        link: ../dev/make.d2
        class: _link
      }
      n_zombie_processes: {
        label: "zombie-processes.d2"
        link: ../dev/zombie-processes.d2
        class: _link
      }
    }
    tech_sd_notes_tools: {
      label: "sd-notes/tools"
      grid-columns: 1
      n_NoSQL: {
        label: "NoSQL.d2"
        link: ../sd-notes/tools/NoSQL.d2
        class: _link
      }
      n_RAG: {
        label: "RAG.d2"
        link: ../sd-notes/tools/RAG.d2
        class: _link
      }
      n_communication: {
        label: "communication.d2"
        link: ../sd-notes/tools/communication.d2
        class: _link
      }
      n_rdbms: {
        label: "rdbms.d2"
        link: ../sd-notes/tools/rdbms.d2
        class: _link
      }
      n_vector_database: {
        label: "vector_database.d2"
        link: ../sd-notes/tools/vector_database.d2
        class: _link
      }
    }
    tech_hi: {
      label: "hi"
      grid-columns: 1
      alembic: {
        label: "alembic.d2"
        link: ../hi/alembic.d2
        class: _link
      }
      n_auth: {
        label: "auth.d2"
        link: ../hi/auth.d2
        class: _link
      }
      n_basic_usage: {
        label: "basic_usage.d2"
        link: ../hi/basic_usage.d2
        class: _link
      }
      n_data_sync: {
        label: "data_sync.d2"
        link: ../hi/data_sync.d2
        class: _link
      }
      n_enrich_glosses: {
        label: "enrich_glosses.d2"
        link: ../hi/enrich_glosses.d2
        class: _link
      }
      n_fetch_text: {
        label: "fetch_text.d2"
        link: ../hi/fetch_text.d2
        class: _link
      }
      n_frontend: {
        label: "frontend.d2"
        link: ../hi/frontend.d2
        class: _link
      }
      n_generate_audio: {
        label: "generate_audio.d2"
        link: ../hi/generate_audio.d2
        class: _link
      }
      n_migration: {
        label: "migration.d2"
        link: ../hi/migration.d2
        class: _link
      }
      n_process_sentences: {
        label: "process_sentences.d2"
        link: ../hi/process_sentences.d2
        class: _link
      }
    }
    _quality: {class: styled}
  }
}
