vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 3
  }
}
classes: @"../../classes"

password
n
minimumNumber: {
  label: def minimumNumber(n, password)
  numbers
  lower_case
  upper_case
  special_characters
  len: {
    label: len()
    class: op
  }
  iterate: {
    label: for char_type in \[ numbers, lower_case, upper_case, special_characters\]
    class: iter
  }
  subtract: {
    label: subtract\n6-len(password)
    class: op
  }
  condition: {
    class: cond
    label: re.search\nchar_type, password
  }
  max: {
    label: max()\n0, subtract
    class: op
  }
  increment: {
    label: +=
    class: op
  }
  missing_length
  missing_types: {
    label: missing_types\ninit 0
  }
  max: {
    label: max
    class: op
  }
  max_last: {
    label: max
    class: op
  }
  numbers -> iterate
  lower_case -> iterate
  upper_case -> iterate
  special_characters -> iterate
  len -> subtract
  iterate -> condition
  subtract -> max
  max -> missing_length
  condition -> increment: {
    class: negative
  }
  increment -> missing_types
  missing_types -> max_last
  missing_length -> max_last
}
n -> minimumNumber
password -> minimumNumber.len
password -> minimumNumber.iterate
