direction: down

vars: @"../../../vars/hackerrank.d2"
**.style.text-transform: none
classes: @"../../../../tags"

_quality: {class: compiles}

countingSort {
  label: countingSort(arr)
  _freq: freq\n\[0\] * 100
  _iter: elem in arr
  _iter -> _freq: += @ i # TODO: where does i come from?
}
