vars: @"../../../vars/hackerrank.d2"
**.style.text-transform: none
classes: @"../../../../tags"

_quality: {class: compiles}



s
marsExploration

design_pattern: {
  label: "design pattern: none"
  link: ../../../design-patterns/none.d2
  class: _link
}
