vars: @"../../../vars/hackerrank.d2"
**.style.text-transform: none
classes: @"../../../classes/tags"
classes: @"../../../classes/function"

_quality: {class: compiles}

pangrams {
  label: pangrams(s)
  _letters: letters\ninit \{\}
  _iter: letter in s.lower()
  _cond_1: letter not in letters.keys()\n& letter != ' '
  _cond_3: {
    label: key count == alphabet count
    class: cond
  }
  _iter -> _cond_1
  _cond_1 -> _letters: add to keys
  _letters -> _cond_3
  _cond_3 -> "pangram": {
    class: positive
  }
  _cond_3 -> "not pangram": {
    class: negative
  }
}
