**.style.text-transform: none
to_add: {
  style: {
    stroke-width: 3
  }
}
to_remove: {
  style: {
    stroke-width: 3
  }
}
unchanged: {
  style: {
    stroke-width: 3
  }
}
future: {
  style: {
    stroke-width: 3
    stroke-dash: 3
  }
}
