**.style.text-transform: none
user: {
  shape: c4-person
  style: {
    font-size: 32
  }
}
highlight: { # debug class - only for temporary use
  style: {
    font-size: 32
    stroke-width: 7
  }
}
frontend: {
  style: {
    font-size: 32
    stroke-width: 5
  }
}
pipeline: {
  style: {
    font-size: 32
    stroke-width: 5
  }
}
api: {
  style: {
    stroke-width: 5
    font-size: 32
  }
}
database: {
  style: {
    font-size: 32
    stroke-width: 5
  }
}
aws: {
  style: {
    font-size: 32
    stroke-width: 5
  }
}
azure: {
  style: {
    stroke-width: 5
    font-size: 32
  }
}
gcp: {
  style: {
    font-size: 32
    stroke-width: 5
  }
}
