vars: @"../../vars/system-design.d2"
classes: @"../../../classes"
classes: @"../../../tags"

_quality: {class: compiles}


client: {
  class: obj_client
  label: Client
}

load_balancer: {
  class: obj_lb
  label: Load Balancer
  
  algorithm: {
    class: cond
    label: Algorithm
  }
  
  health_checker: {
    label: Health Checker
    shape: diamond
  }
}

server_pool: {
  server1: {
    class: obj_server
    label: Server 1
  }
  server2: {
    class: obj_server
    label: Server 2
  }
  server_n: {
    class: obj_server
    label: Server N
  }
}

client -> load_balancer: {class: edge_request}
load_balancer.algorithm -> server_pool.server1: round robin
load_balancer.algorithm -> server_pool.server2: weighted
load_balancer.algorithm -> server_pool.server_n: least conn

load_balancer.health_checker -> server_pool.server1: {class: edge_query}
load_balancer.health_checker -> server_pool.server2: {class: edge_query}
load_balancer.health_checker -> server_pool.server_n: {class: edge_query}

# algorithms: simple, capacity-aware, load-aware, session-sticky, retry-if-unhealthy (health-aware?)

layers: {
  1_strategy_pattern: {
    ...@"../../design-patterns/strategy".layers.1_pattern

    client.label: "Client"
    context.label: "Load Balancer"
    context.execute.label: "pick backend"
    context.slot.label: "algorithm"
    iface.label: "selection algorithm"
    iface.run.label: "choose(server_pool)"
    concrete_a.label: "round robin"
    concrete_b.label: "weighted"
    concrete_c.label: "least connections"

    design_pattern: {
      label: "design pattern: strategy"
      link: ../../design-patterns/strategy.d2
      class: _link
    }
  }
}
