compiles: {
  label: compiles
  shape: oval
  style: {
    stroke: Gray
    stroke-dash: 4
    font-color: Gray
    font-size: 14
  }
}
styled: {
  near: top-right
  label: styled
  shape: oval
  style: {
    stroke: SteelBlue
    stroke-width: 2
    font-color: SteelBlue
    font-size: 14
  }
}
coherent: {
  label: coherent
  shape: oval
  style: {
    stroke: DarkGreen
    stroke-width: 3
    font-color: DarkGreen
    font-size: 14
  }
}
