obj_socket: {
  style: {
    font-size: 20
  }
}
obj_port: {
  style: {
    font-size: 18
  }
}
edge_own: {
  label: 𐑽 # Savian Letter Ear (listens)
  style: {
    stroke-width: 2
    stroke-dash: 2
    stroke: Orange
  }
}
edge_call: {
  label: ☎ # calls
  style: {
    stroke-dash: 4
    stroke: Violet
  }
}
edge_forward: {
  label: → # forwards
  style: {
    stroke-dash: 5
    stroke-width: 2
  }
}
