grid-rows: 4
to_add: {
  style: {
    stroke: DarkGreen
    stroke-width: 3
  }
}
to_remove: {
  style: {
    stroke: DarkRed
    stroke-width: 3
  }
}
unchanged: {
  style: {
    stroke: Gray
    stroke-width: 3
  }
}
