direction: down
vars: @"../../../vars/hackerrank.d2"
**.style.text-transform: none
classes: @"../../../../tags"

_quality: {class: compiles}

birthday: {
  label: birthday(s, d, m)
  iter: iter\; leave space for segment
  # TODO: illustrate "leave space for segment"
  cond: check if segment sums to d
  result
  iter -> cond
  cond -> result: increment
}

