direction: down
vars: @"../../../vars/hackerrank.d2"
**.style.text-transform: none
classes: @"../../../classes/tags"
classes: @"../../../classes/function"

_quality: {class: compiles}

getTotalX: {
  label: getTotalX(a, b)
  iter: max(a) to min(b) inclusive {
    class: iter
  }
  iter_a: {
    label: elem in a
    class: iter
  }
  cond_a: candidate %>% elem == 0 {
    class: cond
  }
  iter_b: {
    label: elem in b
    class: iter
  }
  cond_b: elem %>% candidate == 0 {
    class: cond
  }
  AND: {
    class: gate_and
  }
  eligibility
  result
  iter -> iter_a
  iter -> iter_b
  iter_a -> cond_a
  iter_b -> cond_b
  cond_a -> AND
  cond_b -> AND
  AND -> eligibility
  eligibility -> result: increment
}
