direction: down
vars: @"../../../vars/hackerrank.d2"
**.style.text-transform: none
classes: @"../../../../tags"
classes: @"../../../../classes"

_quality: {class: compiles}

maximumPerimeterTriangle {
  label: maximumPerimeterTriangle(sticks)
  sort: sort\ndescending
  iter: i in range(len(sticks)-2)
    cond: isTriangle\nC < B + A {
      shape: diamond
      y: {
        label: sorted\nedges
        shape: circle
        class: positive
      }
      n: {
        label: "[-1]"
        shape: circle
        class: negative
      }
    }
  result
  sort -> iter
  iter -> cond
  cond.y -> result: {
    class: positive
  }
  cond.n -> result: {
    class: negative
  }
}

design_pattern: {
  label: "design pattern: none"
  link: ../../../design-patterns/none.d2
  class: _link
}
