direction: down
vars: @"../../../vars/hackerrank.d2"
**.style.text-transform: none
classes: @"../../../../tags"

_quality: {class: compiles}

migratoryBirds {
  label: migratoryBirds(arr)
  type_freq: types\ninit\[0\] * 6
  iter: bird in birds # TODO: how is bird actually used?
  iter_freq: type,freq in types
  cond: freq == max(type_freq)
  iter -> type_freq: load
  type_freq -> iter_freq
  iter_freq -> cond
}
result
migratoryBirds.cond -> result

design_pattern: {
  label: "design pattern: none"
  link: ../../../design-patterns/none.d2
  class: _link
}
