direction: right
vars: @"../../../vars/hackerrank.d2"
**.style.text-transform: none
"""
TODO: this probably introduces new syntax; deserves depiction of syntax
"""

classes: @"../../../../tags"

_quality: {class: compiles}

strings_xor: {
  label: strings_xor(s, t)
  iter: i in range(len(s))
  cond: identical {
    shape: diamond
  }
  res: result\ninit \"\"
  iter -> cond
  cond -> res: append '1' {
    style: {
      stroke: darkgreen
    }
  }
  cond -> res: append '0' {
    style: {
      stroke: crimson
    }
  }
}
