vars: @"../../../vars/hackerrank.d2"
**.style.text-transform: none
classes: @"../../../../tags"

_quality: {class: compiles}

twoArrays: {
  label: twoArrays(k, A, B)
  sort
  iter: i in range(len(A))
  cond: A\[i\] + B\[i\] < k {
    shape: diamond
  }
  iter -> cond
  sort -> cond: A
  sort_rev -> cond: B
  cond -> output
}

design_pattern: {
  label: "design pattern: none"
  link: ../../../design-patterns/none.d2
  class: _link
}
