vars: @"../../../vars/hackerrank.d2"
**.style.text-transform: none

classes: @"../../../../classes"
classes: @"../../../../tags"

_quality: {class: compiles}

q: {
  label: q\n\[...\]
  class: generic_node
}
minimumBribes: {
  label: minimumBribes(q)
  n: {
    class: generic_node
  }
  sorted_q: {
    label: sorted_q
    class: generic_node
  }
  iterate: {
    label: "for [i, i, i...] in range(n)"
    class: iter
  }
  same: {
    label: already\nsorted
    class: cond
  }
  bribe_one: {
    label: bribe 1\nq\[i\] == sorted_q\[i + 1\]
    class: cond
  }
  switch_one: {
    label: switch 1\nsorted_q\[i\], \[i + 1\]
    class: op
  }
  switch_one_offset: {
    label: switch 1 offset\nsorted_q\[i + 1\], \[i + 2\]
    class: op
  }
  bribe_two: {
    label: bribe 2\nq\[i\] == sorted_q\[i + 2\]
    class: cond
  }
  print_return: {
    label: print(\"Too chaotic\")\nreturn
    class: op
  }
  total: {
    class: generic_node
  }
  sorted_q -> iterate: {
    class: data
  }
  n -> iterate: {
    class: scalar
  }
  iterate -> same: {
    class: generic_edge
  }
  iterate <- same: continue { class: positive }
  same -> bribe_one: { class: negative }
  bribe_one -> bribe_two: { class: negative }
  switch_one <- bribe_one: { class: positive }
  bribe_one -> total: increment 1: { class: positive }
  switch_one <- bribe_two: { class: positive }
  switch_one_offset <- bribe_two: { class: positive }
  bribe_two -> print_return: { class: negative }
  bribe_two -> total: increment 2: { class: positive }
}
q -> minimumBribes.n: len {
  class: scalar
}
q -> minimumBribes.sorted_q: sort {
  class: data
}
q -> minimumBribes.iterate: {
  class: data
}

design_pattern: {
  label: "design pattern: none"
  link: ../../../design-patterns/none.d2
  class: _link
}
