direction: down
vars: @"../../../vars/hackerrank.d2"
**.style.text-transform: none
classes: @"../../../classes/tags"
classes: @"../../../classes/function"

_quality: {class: compiles}

_countingValleys: countingValleys(steps, path) {
  elevation: elevation\ninit 0
  valleys: valleys\ninit 0
  _iter: step in range(steps)
  _cond: step goes up {
    shape: diamond
    _cond: elevation is neutral {
      shape: diamond
    }
  }
  _iter -> _cond
  _cond._cond -> valleys: increment
  _cond -> elevation: increment {
    class: positive
  }
  _cond -> elevation: decrement {
    class: negative
  }
}
_countingValleys.valleys -> output
