vars: {
  d2-config: {
    theme-id: 201
    layout-engine: elk
  }
}

classes: @"../../../classes/tags"

# TODO: use d2 grid capabilities to illustrate in separate layer

_quality: {class: compiles}

diagonalDifference {
  label: diagonalDifference(arr, n)
  _iter: ndx in range(n) { }
  _diff: abs( diff(_,_) )
  _iter -> descending_sum: increment\narr\[ndx\]\[ndx\]
  _iter -> ascending_sum: increment\narr\[n-1-ndx\]\[ndx\]
  descending_sum -> _diff
  ascending_sum -> _diff
}
