vars: @"../../vars/jbm.d2"
classes: @"../../../tags"

_quality: {class: compiles}

plankton -> formula: will steal
formula: |latex
  \lim_{h \rightarrow 0 } \frac{f(x+h)-f(x)}{h}
|

design_pattern: {
  label: "design pattern: none"
  link: ../../design-patterns/none.d2
  class: _link
}
